# name: morning
# on:
#   schedule:
#   - cron:  '17 * * * *'
#   workflow_dispatch:

# jobs:
#   send_message:
#     runs-on: ubuntu-latest
#     name: exec road

#     steps:
#     - name: checkout
#       uses: actions/checkout@v3
#       with:
#         ref: master

#     - name: sender
#       uses: actions/setup-python@v2
#       with:
#         python-version: '3.7'
#         architecture: 'x64'
#     - run: pip install -r ./requirements.txt && python ./main.py

#     env:
#       APP_ID: ''
#       APP_SECRET: ''
#       TEMPLATE_ID: ''
#       USER_ID: ''
#       START_DATE: '' 
#       BIRTHDAY: ''
#       CITY: ''
